name: "Build and publish container image"
# When a push to the default branch occurs, build and release a "latest" image
# When a tag `vX.Y.Z` push occurs, build and release an image with that tag

on:
  push:
    branches:
      - $default-branch
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"


jobs:

  build-and-release-image:
    uses: "nsidc/.github/.github/workflows/build-and-publish-container-image.yml@main"
    secrets: "inherit"
