name: "Build and publish container image"

on:
  # This is a re-usable workflow!
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
  workflow_call:
    inputs:
      docker-build-path:
        type: "string"
        default: "."
      docker-file-name:
        type: "string"
        default: "Dockerfile"
      docker-image-name:
        type: "string"
        # TODO: Calculate NSIDC org name from variable?
        default: "nsidc/${{ github.event.repository.name }}"
    secrets:
      DOCKER_USER:
        required: true
      DOCKER_PASS:
        required: true


jobs:

  build-and-release-image:
    name: "Build and release container image"
    runs-on: "ubuntu-latest"
    env:
      IMAGE_NAME: "${{ inputs.docker-image-name }}"
      # GitHub Actions expressions don't have great conditional support, so
      # writing a ternary expression looks a lot like bash. In Python, this
      # would read as:
      #     github.ref_name if github.ref_type == 'tag' else 'latest'
      #     https://docs.github.com/en/actions/learn-github-actions/expressions
      IMAGE_TAG: "${{ github.ref_type == 'tag' && github.ref_name || 'latest' }}"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"

      - name: "Build container image"
        run: |
          docker build \
            --file "${{ inputs.docker-file-name }}" \
            --tag "${IMAGE_NAME}:${IMAGE_TAG}" \
            "${{ inputs.docker-build-path }}"

      - name: "DockerHub login"
        uses: "docker/login-action@v2"
        with:
          username: "${{secrets.DOCKER_USER}}"
          password: "${{secrets.DOCKER_PASS}}"

      - name: "GHCR login"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Push to image registries (DockerHub, GHCR)"
        run: |
          # Push to DockerHub
          docker push "${IMAGE_NAME}:${IMAGE_TAG}"

          # Re-tag image and push to GHCR
          docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "ghcr.io/${IMAGE_NAME}:${IMAGE_TAG}"
          docker push "ghcr.io/${IMAGE_NAME}:${IMAGE_TAG}"

          # TODO: quay.io?
          # docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "quay.io/${IMAGE_NAME}:${IMAGE_TAG}"
          # docker push "quay.io/${IMAGE_NAME}:${IMAGE_TAG}"
